export const styles = {
    'page': 'min-h-screen bg-black w-full px-4 lg:px-20 overflow-x-hidden',
    'header-sm': 'text-white font-shippori text-lg md:text-2xl',
    'header-sm-black': 'text-black font-shippori text-2xl',
    'header-md': 'text-white font-shippori text-4xl',
    'header-md-no-color': 'font-shippori text-4xl',
    'header-btwn-mdlg':  'text-white font-shippori text-5xl',
    'header-lg': 'text-white font-shippori text-4xl lg:text-6xl',  
    'header-xl': 'text-white font-shippori text-6xl md:text-5xl lg:text-7xl xl:text-8xl',  
    'subheading': 'text-white font-manrope text-md md:text-lg lg:text-xl font-semibold',
    'button':'border-[1px] bg-black text-black border-white border-[1px] hover:bg-black-pressed transition-all ease-in hover:font-bold rounded-full',
    'button-without-arrow':'py-2 px-5',
    'button-with-diagonal-arrow': 'py-2 px-5 flex gap-x-2 justify-center items-center',
    'blue-button':'border-[1px] text-black border-blue bg-blue hover:bg-blue-pressed hover:border-blue-pressed rounded-full transition-all ease-in hover:font-bold',
    'red-button':'border-[1px] text-black border-red bg-red hover:bg-red-pressed hover:border-red-pressed rounded-full transition-all ease-in hover:font-bold',
    'yellow-button':'border-[1px] text-black border-yellow bg-yellow hover:bg-yellow-pressed hover:border-yellow-pressed rounded-full transition-all ease-in hover:font-bold',
    'button-with-right-arrow':'pl-4 pr-2 py-2 gap-x-1 flex items-center justify-between',
    'subheading-black': 'text-black font-manrope text-xl font-semibold',
    'button-text': 'text-white font-manrope text-lg font-semibold',
    'button-text-black': 'text-black font-manrope text-lg font-semibold',
    'navbar-link': 'text-white font-manrope text-lg hover:font-bold transition-all ease-in relative inline-block group',
    'navbar-underline': "absolute left-0 bottom-0 h-0.5 w-0 bg-white transition-all duration-300 ease-in-out group-hover:w-full",
    'exp-link': 'text-white font-manrope font-semibold text-sm hover:font-bold transition-all ease-in relative inline-block group',
    'exp-position': 'text-white font-manrope font-semibold text-lg',
    'exp-period': 'text-white font-manrope font-semibold text-md',
    'mini-subheader': 'font-bold text-md font-shippori text-yellow tracking-widest',
    'project-container': 'border-[1px] border-white rounded-xl py-4 px-8',
    'paragraph-text': "text-white font-manrope text-justify",
}