export const styles = {
    'page': 'min-h-screen bg-black w-full p-20',
    'header-sm': 'text-white font-shippori text-2xl',
    'header-md': 'text-white font-shippori text-4xl',
    'header-md-no-color': 'font-shippori text-4xl',
    'header-sm-black': 'text-black font-shippori text-2xl',
    'header-xl': 'text-white font-shippori text-8xl',  
    'subheading': 'text-white font-manrope text-xl font-semibold',
    'button':'border-[1px] bg-black text-black border-white border-[1px] hover:bg-black-pressed transition-all ease-in hover:font-bold rounded-full',
    'button-without-arrow':'py-2 px-5',
    'button-with-diagonal-arrow': 'py-2 px-5 flex gap-x-2 justify-center items-center',
    'blue-button':'border-[1px] text-black border-blue bg-blue hover:bg-blue-pressed hover:border-blue-pressed rounded-full transition-all ease-in hover:font-bold',
    'red-button':'border-[1px] text-black border-red bg-red hover:bg-red-pressed hover:border-red-pressed rounded-full transition-all ease-in hover:font-bold',
    'yellow-button':'border-[1px] text-black border-yellow bg-yellow hover:bg-yellow-pressed hover:border-yellow-pressed rounded-full transition-all ease-in hover:font-bold',
    'button-with-right-arrow':'pl-4 pr-2 py-2 gap-x-1 flex items-center justify-between',
    'subheading-black': 'text-black font-manrope text-xl font-semibold',
    'button-text': 'text-white font-manrope text-lg font-semibold',
    'button-text-black': 'text-black font-manrope text-lg font-semibold',
    'navbar-link': 'text-white font-manrope text-lg hover:font-bold transition-all ease-in relative inline-block group',
    'navbar-underline': "absolute left-0 bottom-0 h-0.5 w-0 bg-white transition-all duration-300 ease-in-out group-hover:w-full",
    'exp-link': 'text-white font-manrope font-semibold text-sm hover:font-bold transition-all ease-in relative inline-block group',
    'exp-position': 'text-white font-manrope font-semibold text-lg',
    'exp-period': 'text-white font-manrope font-semibold text-md',
}